use phf::phf_map;
use rdev::Key;

pub const KEYPRESS_MAP: phf::Map<char, Key> = phf_map! {
    'a' => Key::KeyA,
    'b' => Key::KeyB,
    'c' => Key::KeyC,
    'd' => Key::KeyD,
    'e' => Key::KeyE,
    'f' => Key::KeyF,
    'g' => Key::KeyG,
    'h' => Key::KeyH,
    'i' => Key::KeyI,
    'j' => Key::KeyJ,
    'k' => Key::KeyK,
    'l' => Key::KeyL,
    'm' => Key::KeyM,
    'n' => Key::KeyN,
    'o' => Key::KeyO,
    'p' => Key::KeyP,
    'q' => Key::KeyQ,
    'r' => Key::KeyR,
    's' => Key::KeyS,
    't' => Key::KeyT,
    'u' => Key::KeyU,
    'v' => Key::KeyV,
    'w' => Key::KeyW,
    'x' => Key::KeyX,
    'y' => Key::KeyY,
    'z' => Key::KeyZ,
    ' ' => Key::Space,
    '\'' => Key::Quote,
    '/' => Key::Slash,
};
